import type { Metadata } from "next";
import { Noto_Sans_Display } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";

const geistSans = Noto_Sans_Display({
  variable: "--font-geist-sans",
  weight: ["100", "900"],
  subsets: ["latin"]
});
const geistMono = Noto_Sans_Display({
  variable: "--font-geist-mono",
  weight: ["100", "900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "AppAcademy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
